#ifndef CALCULATEPLUGIN_GLOBAL_H
#define CALCULATEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CALCULATEPLUGIN_LIBRARY)
#  define CALCULATEPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define CALCULATEPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // CALCULATEPLUGIN_GLOBAL_H
